// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bjyfkqffsyuyzmfztdrz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJqeWZrcWZmc3l1eXptZnp0ZHJ6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc4MTQzNTUsImV4cCI6MjA2MzM5MDM1NX0.XL_UrXmOa1K9w5uHGZxoFRj8imGpmS_BXu67ev0Pe8s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);